"use client";
import Home from "./page/Home/Home.js";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function page() {
  return (
    <div>
      <Home />
    </div>
  );
}
